### PR TITLE
feat: selected character message on-spawn

### PR DESCRIPTION
**Pull request by traditionalism**
Requested in discord, config-toggle. Picture example below.

Screenshot 2022-08-10 022821

### CODE REVIEW

**Comment by traditionalism** [comment]
Seems to sometimes be a little weird so Andy might have to mess with it.

**Comment by traditionalism** [comment]
With this, it will only work if you use the '/changecharacter' command, otherwise if you just joined and haven't selected a character yet. 'local character = NDCore.Functions.GetSelectedCharacter()' won't return anything.

**Comment by Kolo2016** [comment]
There is one slight issue with this when you change character it will 
either duplicate the message or not say the correct name.

Screenshot 2022-08-10 233716

**Comment by traditionalism** [comment]
Resolved conflicts.

**Comment by Andyyy7666** [comment]
I get that it looks good but I don't feel like it's a necessary feature, the player already selects what character to play as so there's no purpose of sending it in the chat again.

**Comment by traditionalism** [comment]
> 

I suppose, but the config option is there for a reason. As-well as it defaults to off.

**Pull request closed without merging**
